/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.nearsyh.mafia.protos.Character', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.CharacterIndex', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.CharacterType', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.Event', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.EventType', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.Game', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.GameStatus', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.Player', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.Template', null, global);
goog.exportSymbol('proto.com.nearsyh.mafia.protos.TurnStatus', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.TurnStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.nearsyh.mafia.protos.TurnStatus.repeatedFields_, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.TurnStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.TurnStatus.displayName = 'proto.com.nearsyh.mafia.protos.TurnStatus';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.nearsyh.mafia.protos.TurnStatus.repeatedFields_ = [12,13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.TurnStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.TurnStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.TurnStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    frozenPlayerIndex: jspb.Message.getFieldWithDefault(msg, 1, 0),
    toastPlayerIndex: jspb.Message.getFieldWithDefault(msg, 2, 0),
    injectionCharacterIndex: (f = msg.getInjectionCharacterIndex()) && proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(includeInstance, f),
    guardCharacterIndex: (f = msg.getGuardCharacterIndex()) && proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(includeInstance, f),
    killCharacterIndex: (f = msg.getKillCharacterIndex()) && proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(includeInstance, f),
    hasAffection: jspb.Message.getFieldWithDefault(msg, 6, false),
    affectedCharacter: (f = msg.getAffectedCharacter()) && proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(includeInstance, f),
    cureCharacterIndex: (f = msg.getCureCharacterIndex()) && proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(includeInstance, f),
    toxicCharacterIndex: (f = msg.getToxicCharacterIndex()) && proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(includeInstance, f),
    verifyCharacterIndex: (f = msg.getVerifyCharacterIndex()) && proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(includeInstance, f),
    mutedPlayerIndex: jspb.Message.getFieldWithDefault(msg, 11, 0),
    deadCharactersList: jspb.Message.toObjectList(msg.getDeadCharactersList(),
    proto.com.nearsyh.mafia.protos.CharacterIndex.toObject, includeInstance),
    votedCharactersList: jspb.Message.toObjectList(msg.getVotedCharactersList(),
    proto.com.nearsyh.mafia.protos.CharacterIndex.toObject, includeInstance),
    isMoonDead: jspb.Message.getFieldWithDefault(msg, 14, false),
    isSunDead: jspb.Message.getFieldWithDefault(msg, 15, false),
    isPrincessDead: jspb.Message.getFieldWithDefault(msg, 16, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.TurnStatus}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.TurnStatus;
  return proto.com.nearsyh.mafia.protos.TurnStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.TurnStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.TurnStatus}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFrozenPlayerIndex(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setToastPlayerIndex(value);
      break;
    case 3:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.setInjectionCharacterIndex(value);
      break;
    case 4:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.setGuardCharacterIndex(value);
      break;
    case 5:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.setKillCharacterIndex(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasAffection(value);
      break;
    case 7:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.setAffectedCharacter(value);
      break;
    case 8:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.setCureCharacterIndex(value);
      break;
    case 9:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.setToxicCharacterIndex(value);
      break;
    case 10:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.setVerifyCharacterIndex(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMutedPlayerIndex(value);
      break;
    case 12:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.addDeadCharacters(value);
      break;
    case 13:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.addVotedCharacters(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsMoonDead(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsSunDead(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPrincessDead(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.TurnStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.TurnStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.TurnStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrozenPlayerIndex();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getToastPlayerIndex();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getInjectionCharacterIndex();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getGuardCharacterIndex();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getKillCharacterIndex();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getHasAffection();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getAffectedCharacter();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getCureCharacterIndex();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getToxicCharacterIndex();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getVerifyCharacterIndex();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getMutedPlayerIndex();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getDeadCharactersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getVotedCharactersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getIsMoonDead();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getIsSunDead();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getIsPrincessDead();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
};


/**
 * optional int32 frozen_player_index = 1;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getFrozenPlayerIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setFrozenPlayerIndex = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 toast_player_index = 2;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getToastPlayerIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setToastPlayerIndex = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional CharacterIndex injection_character_index = 3;
 * @return {?proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getInjectionCharacterIndex = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.CharacterIndex} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 3));
};


/** @param {?proto.com.nearsyh.mafia.protos.CharacterIndex|undefined} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setInjectionCharacterIndex = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearInjectionCharacterIndex = function() {
  this.setInjectionCharacterIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.hasInjectionCharacterIndex = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CharacterIndex guard_character_index = 4;
 * @return {?proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getGuardCharacterIndex = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.CharacterIndex} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 4));
};


/** @param {?proto.com.nearsyh.mafia.protos.CharacterIndex|undefined} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setGuardCharacterIndex = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearGuardCharacterIndex = function() {
  this.setGuardCharacterIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.hasGuardCharacterIndex = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional CharacterIndex kill_character_index = 5;
 * @return {?proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getKillCharacterIndex = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.CharacterIndex} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 5));
};


/** @param {?proto.com.nearsyh.mafia.protos.CharacterIndex|undefined} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setKillCharacterIndex = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearKillCharacterIndex = function() {
  this.setKillCharacterIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.hasKillCharacterIndex = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool has_affection = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getHasAffection = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setHasAffection = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional CharacterIndex affected_character = 7;
 * @return {?proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getAffectedCharacter = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.CharacterIndex} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 7));
};


/** @param {?proto.com.nearsyh.mafia.protos.CharacterIndex|undefined} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setAffectedCharacter = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearAffectedCharacter = function() {
  this.setAffectedCharacter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.hasAffectedCharacter = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional CharacterIndex cure_character_index = 8;
 * @return {?proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getCureCharacterIndex = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.CharacterIndex} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 8));
};


/** @param {?proto.com.nearsyh.mafia.protos.CharacterIndex|undefined} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setCureCharacterIndex = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearCureCharacterIndex = function() {
  this.setCureCharacterIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.hasCureCharacterIndex = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional CharacterIndex toxic_character_index = 9;
 * @return {?proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getToxicCharacterIndex = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.CharacterIndex} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 9));
};


/** @param {?proto.com.nearsyh.mafia.protos.CharacterIndex|undefined} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setToxicCharacterIndex = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearToxicCharacterIndex = function() {
  this.setToxicCharacterIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.hasToxicCharacterIndex = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional CharacterIndex verify_character_index = 10;
 * @return {?proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getVerifyCharacterIndex = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.CharacterIndex} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 10));
};


/** @param {?proto.com.nearsyh.mafia.protos.CharacterIndex|undefined} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setVerifyCharacterIndex = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearVerifyCharacterIndex = function() {
  this.setVerifyCharacterIndex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.hasVerifyCharacterIndex = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int32 muted_player_index = 11;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getMutedPlayerIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setMutedPlayerIndex = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * repeated CharacterIndex dead_characters = 12;
 * @return {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getDeadCharactersList = function() {
  return /** @type{!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 12));
};


/** @param {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setDeadCharactersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.addDeadCharacters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.com.nearsyh.mafia.protos.CharacterIndex, opt_index);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearDeadCharactersList = function() {
  this.setDeadCharactersList([]);
};


/**
 * repeated CharacterIndex voted_characters = 13;
 * @return {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getVotedCharactersList = function() {
  return /** @type{!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 13));
};


/** @param {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setVotedCharactersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.addVotedCharacters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.com.nearsyh.mafia.protos.CharacterIndex, opt_index);
};


proto.com.nearsyh.mafia.protos.TurnStatus.prototype.clearVotedCharactersList = function() {
  this.setVotedCharactersList([]);
};


/**
 * optional bool is_moon_dead = 14;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getIsMoonDead = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 14, false));
};


/** @param {boolean} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setIsMoonDead = function(value) {
  jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional bool is_sun_dead = 15;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getIsSunDead = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 15, false));
};


/** @param {boolean} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setIsSunDead = function(value) {
  jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional bool is_princess_dead = 16;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.getIsPrincessDead = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 16, false));
};


/** @param {boolean} value */
proto.com.nearsyh.mafia.protos.TurnStatus.prototype.setIsPrincessDead = function(value) {
  jspb.Message.setProto3BooleanField(this, 16, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.GameStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.nearsyh.mafia.protos.GameStatus.repeatedFields_, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.GameStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.GameStatus.displayName = 'proto.com.nearsyh.mafia.protos.GameStatus';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.nearsyh.mafia.protos.GameStatus.repeatedFields_ = [7,8,9,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.GameStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.GameStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.GameStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    isCureUsed: jspb.Message.getFieldWithDefault(msg, 1, false),
    isToxicUsed: jspb.Message.getFieldWithDefault(msg, 2, false),
    idolIndex: jspb.Message.getFieldWithDefault(msg, 3, 0),
    loverIndex: jspb.Message.getFieldWithDefault(msg, 4, 0),
    pardonIndex: jspb.Message.getFieldWithDefault(msg, 5, 0),
    duelIndex: jspb.Message.getFieldWithDefault(msg, 6, 0),
    deadCharactersList: jspb.Message.toObjectList(msg.getDeadCharactersList(),
    proto.com.nearsyh.mafia.protos.CharacterIndex.toObject, includeInstance),
    aliveCharactersList: jspb.Message.toObjectList(msg.getAliveCharactersList(),
    proto.com.nearsyh.mafia.protos.CharacterIndex.toObject, includeInstance),
    affectedCharactersList: jspb.Message.toObjectList(msg.getAffectedCharactersList(),
    proto.com.nearsyh.mafia.protos.CharacterIndex.toObject, includeInstance),
    onSurfaceWolvesList: jspb.Message.getRepeatedField(msg, 10)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.GameStatus}
 */
proto.com.nearsyh.mafia.protos.GameStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.GameStatus;
  return proto.com.nearsyh.mafia.protos.GameStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.GameStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.GameStatus}
 */
proto.com.nearsyh.mafia.protos.GameStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsCureUsed(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsToxicUsed(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIdolIndex(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLoverIndex(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPardonIndex(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDuelIndex(value);
      break;
    case 7:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.addDeadCharacters(value);
      break;
    case 8:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.addAliveCharacters(value);
      break;
    case 9:
      var value = new proto.com.nearsyh.mafia.protos.CharacterIndex;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader);
      msg.addAffectedCharacters(value);
      break;
    case 10:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setOnSurfaceWolvesList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.GameStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.GameStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.GameStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsCureUsed();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getIsToxicUsed();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getIdolIndex();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getLoverIndex();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getPardonIndex();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getDuelIndex();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getDeadCharactersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getAliveCharactersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getAffectedCharactersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter
    );
  }
  f = message.getOnSurfaceWolvesList();
  if (f.length > 0) {
    writer.writePackedInt32(
      10,
      f
    );
  }
};


/**
 * optional bool is_cure_used = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getIsCureUsed = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setIsCureUsed = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool is_toxic_used = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getIsToxicUsed = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setIsToxicUsed = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int32 idol_index = 3;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getIdolIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setIdolIndex = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 lover_index = 4;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getLoverIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setLoverIndex = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 pardon_index = 5;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getPardonIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setPardonIndex = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 duel_index = 6;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getDuelIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setDuelIndex = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated CharacterIndex dead_characters = 7;
 * @return {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getDeadCharactersList = function() {
  return /** @type{!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 7));
};


/** @param {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setDeadCharactersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.addDeadCharacters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.com.nearsyh.mafia.protos.CharacterIndex, opt_index);
};


proto.com.nearsyh.mafia.protos.GameStatus.prototype.clearDeadCharactersList = function() {
  this.setDeadCharactersList([]);
};


/**
 * repeated CharacterIndex alive_characters = 8;
 * @return {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getAliveCharactersList = function() {
  return /** @type{!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 8));
};


/** @param {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setAliveCharactersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.addAliveCharacters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.com.nearsyh.mafia.protos.CharacterIndex, opt_index);
};


proto.com.nearsyh.mafia.protos.GameStatus.prototype.clearAliveCharactersList = function() {
  this.setAliveCharactersList([]);
};


/**
 * repeated CharacterIndex affected_characters = 9;
 * @return {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getAffectedCharactersList = function() {
  return /** @type{!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.nearsyh.mafia.protos.CharacterIndex, 9));
};


/** @param {!Array<!proto.com.nearsyh.mafia.protos.CharacterIndex>} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setAffectedCharactersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.addAffectedCharacters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.com.nearsyh.mafia.protos.CharacterIndex, opt_index);
};


proto.com.nearsyh.mafia.protos.GameStatus.prototype.clearAffectedCharactersList = function() {
  this.setAffectedCharactersList([]);
};


/**
 * repeated int32 on_surface_wolves = 10;
 * @return {!Array<number>}
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.getOnSurfaceWolvesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 10));
};


/** @param {!Array<number>} value */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.setOnSurfaceWolvesList = function(value) {
  jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.com.nearsyh.mafia.protos.GameStatus.prototype.addOnSurfaceWolves = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


proto.com.nearsyh.mafia.protos.GameStatus.prototype.clearOnSurfaceWolvesList = function() {
  this.setOnSurfaceWolvesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.Game = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.nearsyh.mafia.protos.Game.repeatedFields_, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.Game, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.Game.displayName = 'proto.com.nearsyh.mafia.protos.Game';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.nearsyh.mafia.protos.Game.repeatedFields_ = [2,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.Game.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.Game} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Game.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    playersList: jspb.Message.toObjectList(msg.getPlayersList(),
    proto.com.nearsyh.mafia.protos.Player.toObject, includeInstance),
    turnId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    lastTurn: (f = msg.getLastTurn()) && proto.com.nearsyh.mafia.protos.TurnStatus.toObject(includeInstance, f),
    currentTurn: (f = msg.getCurrentTurn()) && proto.com.nearsyh.mafia.protos.TurnStatus.toObject(includeInstance, f),
    pastTurnsList: jspb.Message.toObjectList(msg.getPastTurnsList(),
    proto.com.nearsyh.mafia.protos.TurnStatus.toObject, includeInstance),
    gameStatus: (f = msg.getGameStatus()) && proto.com.nearsyh.mafia.protos.GameStatus.toObject(includeInstance, f),
    nextEvent: (f = msg.getNextEvent()) && proto.com.nearsyh.mafia.protos.Event.toObject(includeInstance, f),
    startTimestamp: jspb.Message.getFieldWithDefault(msg, 11, 0),
    endTimestamp: jspb.Message.getFieldWithDefault(msg, 12, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.Game}
 */
proto.com.nearsyh.mafia.protos.Game.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.Game;
  return proto.com.nearsyh.mafia.protos.Game.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.Game} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.Game}
 */
proto.com.nearsyh.mafia.protos.Game.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.com.nearsyh.mafia.protos.Player;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.Player.deserializeBinaryFromReader);
      msg.addPlayers(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTurnId(value);
      break;
    case 4:
      var value = new proto.com.nearsyh.mafia.protos.TurnStatus;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.TurnStatus.deserializeBinaryFromReader);
      msg.setLastTurn(value);
      break;
    case 5:
      var value = new proto.com.nearsyh.mafia.protos.TurnStatus;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.TurnStatus.deserializeBinaryFromReader);
      msg.setCurrentTurn(value);
      break;
    case 6:
      var value = new proto.com.nearsyh.mafia.protos.TurnStatus;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.TurnStatus.deserializeBinaryFromReader);
      msg.addPastTurns(value);
      break;
    case 7:
      var value = new proto.com.nearsyh.mafia.protos.GameStatus;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.GameStatus.deserializeBinaryFromReader);
      msg.setGameStatus(value);
      break;
    case 8:
      var value = new proto.com.nearsyh.mafia.protos.Event;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.Event.deserializeBinaryFromReader);
      msg.setNextEvent(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartTimestamp(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.Game.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.Game} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Game.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlayersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.com.nearsyh.mafia.protos.Player.serializeBinaryToWriter
    );
  }
  f = message.getTurnId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getLastTurn();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.nearsyh.mafia.protos.TurnStatus.serializeBinaryToWriter
    );
  }
  f = message.getCurrentTurn();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.nearsyh.mafia.protos.TurnStatus.serializeBinaryToWriter
    );
  }
  f = message.getPastTurnsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.com.nearsyh.mafia.protos.TurnStatus.serializeBinaryToWriter
    );
  }
  f = message.getGameStatus();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.com.nearsyh.mafia.protos.GameStatus.serializeBinaryToWriter
    );
  }
  f = message.getNextEvent();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.com.nearsyh.mafia.protos.Event.serializeBinaryToWriter
    );
  }
  f = message.getStartTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getEndTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Player players = 2;
 * @return {!Array<!proto.com.nearsyh.mafia.protos.Player>}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getPlayersList = function() {
  return /** @type{!Array<!proto.com.nearsyh.mafia.protos.Player>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.nearsyh.mafia.protos.Player, 2));
};


/** @param {!Array<!proto.com.nearsyh.mafia.protos.Player>} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setPlayersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.com.nearsyh.mafia.protos.Player=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.nearsyh.mafia.protos.Player}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.addPlayers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.com.nearsyh.mafia.protos.Player, opt_index);
};


proto.com.nearsyh.mafia.protos.Game.prototype.clearPlayersList = function() {
  this.setPlayersList([]);
};


/**
 * optional int32 turn_id = 3;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getTurnId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setTurnId = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional TurnStatus last_turn = 4;
 * @return {?proto.com.nearsyh.mafia.protos.TurnStatus}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getLastTurn = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.TurnStatus} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.TurnStatus, 4));
};


/** @param {?proto.com.nearsyh.mafia.protos.TurnStatus|undefined} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setLastTurn = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.com.nearsyh.mafia.protos.Game.prototype.clearLastTurn = function() {
  this.setLastTurn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.hasLastTurn = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional TurnStatus current_turn = 5;
 * @return {?proto.com.nearsyh.mafia.protos.TurnStatus}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getCurrentTurn = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.TurnStatus} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.TurnStatus, 5));
};


/** @param {?proto.com.nearsyh.mafia.protos.TurnStatus|undefined} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setCurrentTurn = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.com.nearsyh.mafia.protos.Game.prototype.clearCurrentTurn = function() {
  this.setCurrentTurn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.hasCurrentTurn = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated TurnStatus past_turns = 6;
 * @return {!Array<!proto.com.nearsyh.mafia.protos.TurnStatus>}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getPastTurnsList = function() {
  return /** @type{!Array<!proto.com.nearsyh.mafia.protos.TurnStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.nearsyh.mafia.protos.TurnStatus, 6));
};


/** @param {!Array<!proto.com.nearsyh.mafia.protos.TurnStatus>} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setPastTurnsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.com.nearsyh.mafia.protos.TurnStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.nearsyh.mafia.protos.TurnStatus}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.addPastTurns = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.com.nearsyh.mafia.protos.TurnStatus, opt_index);
};


proto.com.nearsyh.mafia.protos.Game.prototype.clearPastTurnsList = function() {
  this.setPastTurnsList([]);
};


/**
 * optional GameStatus game_status = 7;
 * @return {?proto.com.nearsyh.mafia.protos.GameStatus}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getGameStatus = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.GameStatus} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.GameStatus, 7));
};


/** @param {?proto.com.nearsyh.mafia.protos.GameStatus|undefined} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setGameStatus = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.com.nearsyh.mafia.protos.Game.prototype.clearGameStatus = function() {
  this.setGameStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.hasGameStatus = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Event next_event = 8;
 * @return {?proto.com.nearsyh.mafia.protos.Event}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getNextEvent = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.Event} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.Event, 8));
};


/** @param {?proto.com.nearsyh.mafia.protos.Event|undefined} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setNextEvent = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.com.nearsyh.mafia.protos.Game.prototype.clearNextEvent = function() {
  this.setNextEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.hasNextEvent = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int64 start_timestamp = 11;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getStartTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setStartTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int64 end_timestamp = 12;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Game.prototype.getEndTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Game.prototype.setEndTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 12, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.Player = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.Player, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.Player.displayName = 'proto.com.nearsyh.mafia.protos.Player';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.Player.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.Player.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.Player} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Player.toObject = function(includeInstance, msg) {
  var f, obj = {
    characterTop: (f = msg.getCharacterTop()) && proto.com.nearsyh.mafia.protos.Character.toObject(includeInstance, f),
    characterBot: (f = msg.getCharacterBot()) && proto.com.nearsyh.mafia.protos.Character.toObject(includeInstance, f),
    index: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.Player}
 */
proto.com.nearsyh.mafia.protos.Player.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.Player;
  return proto.com.nearsyh.mafia.protos.Player.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.Player} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.Player}
 */
proto.com.nearsyh.mafia.protos.Player.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.nearsyh.mafia.protos.Character;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.Character.deserializeBinaryFromReader);
      msg.setCharacterTop(value);
      break;
    case 2:
      var value = new proto.com.nearsyh.mafia.protos.Character;
      reader.readMessage(value,proto.com.nearsyh.mafia.protos.Character.deserializeBinaryFromReader);
      msg.setCharacterBot(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIndex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.Player.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.Player.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.Player} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Player.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCharacterTop();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.nearsyh.mafia.protos.Character.serializeBinaryToWriter
    );
  }
  f = message.getCharacterBot();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.nearsyh.mafia.protos.Character.serializeBinaryToWriter
    );
  }
  f = message.getIndex();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional Character character_top = 1;
 * @return {?proto.com.nearsyh.mafia.protos.Character}
 */
proto.com.nearsyh.mafia.protos.Player.prototype.getCharacterTop = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.Character} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.Character, 1));
};


/** @param {?proto.com.nearsyh.mafia.protos.Character|undefined} value */
proto.com.nearsyh.mafia.protos.Player.prototype.setCharacterTop = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.nearsyh.mafia.protos.Player.prototype.clearCharacterTop = function() {
  this.setCharacterTop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.Player.prototype.hasCharacterTop = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Character character_bot = 2;
 * @return {?proto.com.nearsyh.mafia.protos.Character}
 */
proto.com.nearsyh.mafia.protos.Player.prototype.getCharacterBot = function() {
  return /** @type{?proto.com.nearsyh.mafia.protos.Character} */ (
    jspb.Message.getWrapperField(this, proto.com.nearsyh.mafia.protos.Character, 2));
};


/** @param {?proto.com.nearsyh.mafia.protos.Character|undefined} value */
proto.com.nearsyh.mafia.protos.Player.prototype.setCharacterBot = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.com.nearsyh.mafia.protos.Player.prototype.clearCharacterBot = function() {
  this.setCharacterBot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.nearsyh.mafia.protos.Player.prototype.hasCharacterBot = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 index = 3;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Player.prototype.getIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Player.prototype.setIndex = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.CharacterIndex = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.CharacterIndex, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.CharacterIndex.displayName = 'proto.com.nearsyh.mafia.protos.CharacterIndex';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.CharacterIndex.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerIndex: jspb.Message.getFieldWithDefault(msg, 1, 0),
    characterIndex: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.CharacterIndex;
  return proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.CharacterIndex}
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayerIndex(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCharacterIndex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.CharacterIndex} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerIndex();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCharacterIndex();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 player_index = 1;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.prototype.getPlayerIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.CharacterIndex.prototype.setPlayerIndex = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 character_index = 2;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.CharacterIndex.prototype.getCharacterIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.CharacterIndex.prototype.setCharacterIndex = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.Character = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.Character, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.Character.displayName = 'proto.com.nearsyh.mafia.protos.Character';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.Character.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.Character.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.Character} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Character.toObject = function(includeInstance, msg) {
  var f, obj = {
    characterType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    isDead: jspb.Message.getFieldWithDefault(msg, 2, false),
    injectionCount: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.Character}
 */
proto.com.nearsyh.mafia.protos.Character.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.Character;
  return proto.com.nearsyh.mafia.protos.Character.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.Character} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.Character}
 */
proto.com.nearsyh.mafia.protos.Character.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.nearsyh.mafia.protos.CharacterType} */ (reader.readEnum());
      msg.setCharacterType(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsDead(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInjectionCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.Character.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.Character.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.Character} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Character.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCharacterType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getIsDead();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getInjectionCount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional CharacterType character_type = 1;
 * @return {!proto.com.nearsyh.mafia.protos.CharacterType}
 */
proto.com.nearsyh.mafia.protos.Character.prototype.getCharacterType = function() {
  return /** @type {!proto.com.nearsyh.mafia.protos.CharacterType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.nearsyh.mafia.protos.CharacterType} value */
proto.com.nearsyh.mafia.protos.Character.prototype.setCharacterType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool is_dead = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.nearsyh.mafia.protos.Character.prototype.getIsDead = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.com.nearsyh.mafia.protos.Character.prototype.setIsDead = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int32 injection_count = 3;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Character.prototype.getInjectionCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Character.prototype.setInjectionCount = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.Event = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.nearsyh.mafia.protos.Event.repeatedFields_, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.Event, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.Event.displayName = 'proto.com.nearsyh.mafia.protos.Event';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.nearsyh.mafia.protos.Event.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.Event.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.Event} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Event.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    candidateTargetsList: jspb.Message.getRepeatedField(msg, 2),
    targetsList: jspb.Message.getRepeatedField(msg, 3),
    timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
    turnId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    lastEventResponse: jspb.Message.getFieldWithDefault(msg, 6, ""),
    currentEventResponse: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.Event}
 */
proto.com.nearsyh.mafia.protos.Event.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.Event;
  return proto.com.nearsyh.mafia.protos.Event.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.Event} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.Event}
 */
proto.com.nearsyh.mafia.protos.Event.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.nearsyh.mafia.protos.EventType} */ (reader.readEnum());
      msg.setEventType(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setCandidateTargetsList(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setTargetsList(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTurnId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastEventResponse(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentEventResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.Event.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.Event} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Event.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCandidateTargetsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
  f = message.getTargetsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getTurnId();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getLastEventResponse();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCurrentEventResponse();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional EventType event_type = 1;
 * @return {!proto.com.nearsyh.mafia.protos.EventType}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.getEventType = function() {
  return /** @type {!proto.com.nearsyh.mafia.protos.EventType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.nearsyh.mafia.protos.EventType} value */
proto.com.nearsyh.mafia.protos.Event.prototype.setEventType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated int32 candidate_targets = 2;
 * @return {!Array<number>}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.getCandidateTargetsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<number>} value */
proto.com.nearsyh.mafia.protos.Event.prototype.setCandidateTargetsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.com.nearsyh.mafia.protos.Event.prototype.addCandidateTargets = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.com.nearsyh.mafia.protos.Event.prototype.clearCandidateTargetsList = function() {
  this.setCandidateTargetsList([]);
};


/**
 * repeated int32 targets = 3;
 * @return {!Array<number>}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.getTargetsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<number>} value */
proto.com.nearsyh.mafia.protos.Event.prototype.setTargetsList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.com.nearsyh.mafia.protos.Event.prototype.addTargets = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.com.nearsyh.mafia.protos.Event.prototype.clearTargetsList = function() {
  this.setTargetsList([]);
};


/**
 * optional int64 timestamp = 4;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Event.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 turn_id = 5;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.getTurnId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Event.prototype.setTurnId = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string last_event_response = 6;
 * @return {string}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.getLastEventResponse = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.com.nearsyh.mafia.protos.Event.prototype.setLastEventResponse = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string current_event_response = 7;
 * @return {string}
 */
proto.com.nearsyh.mafia.protos.Event.prototype.getCurrentEventResponse = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.com.nearsyh.mafia.protos.Event.prototype.setCurrentEventResponse = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.nearsyh.mafia.protos.Template = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.nearsyh.mafia.protos.Template, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.nearsyh.mafia.protos.Template.displayName = 'proto.com.nearsyh.mafia.protos.Template';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.nearsyh.mafia.protos.Template.prototype.toObject = function(opt_includeInstance) {
  return proto.com.nearsyh.mafia.protos.Template.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.nearsyh.mafia.protos.Template} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Template.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    playersNumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    countsMap: (f = msg.getCountsMap()) ? f.toObject(includeInstance, undefined) : [],
    accessTimes: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.nearsyh.mafia.protos.Template}
 */
proto.com.nearsyh.mafia.protos.Template.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.nearsyh.mafia.protos.Template;
  return proto.com.nearsyh.mafia.protos.Template.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.nearsyh.mafia.protos.Template} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.nearsyh.mafia.protos.Template}
 */
proto.com.nearsyh.mafia.protos.Template.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayersNumber(value);
      break;
    case 3:
      var value = msg.getCountsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt32, null, "");
         });
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAccessTimes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.nearsyh.mafia.protos.Template.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.nearsyh.mafia.protos.Template.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.nearsyh.mafia.protos.Template} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.nearsyh.mafia.protos.Template.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlayersNumber();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCountsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt32);
  }
  f = message.getAccessTimes();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.nearsyh.mafia.protos.Template.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.nearsyh.mafia.protos.Template.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 players_number = 2;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Template.prototype.getPlayersNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Template.prototype.setPlayersNumber = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * map<string, int32> counts = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.com.nearsyh.mafia.protos.Template.prototype.getCountsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


proto.com.nearsyh.mafia.protos.Template.prototype.clearCountsMap = function() {
  this.getCountsMap().clear();
};


/**
 * optional int32 access_times = 4;
 * @return {number}
 */
proto.com.nearsyh.mafia.protos.Template.prototype.getAccessTimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.com.nearsyh.mafia.protos.Template.prototype.setAccessTimes = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.com.nearsyh.mafia.protos.CharacterType = {
  CHARACTER_TYPE_UNSPECIFIED: 0,
  NORMAL_VILLAGER: 1,
  WEREWOLF: 2,
  SEER: 3,
  DOCTOR: 4,
  WITCH: 5,
  GUARDIAN: 6,
  PENGUIN: 7,
  TOAST_BAKER: 8,
  WOLF_BEAUTY: 9,
  WOLF_CHILD: 10,
  SUCCUBUS: 11,
  MUTER: 12,
  PRINCESS: 13,
  KNIGHT: 14,
  FOX: 15,
  MOON: 16,
  SUN: 17
};

/**
 * @enum {number}
 */
proto.com.nearsyh.mafia.protos.EventType = {
  EVENT_TYPE_UNSPECIFIED: 0,
  SUNSET: 1,
  CHOOSE_IDOL: 2,
  CHOOSE_LOVER: 3,
  FREEZE: 4,
  TOAST: 5,
  INJECT: 6,
  GUARD: 7,
  KILL: 8,
  AFFECT: 9,
  CURE: 10,
  TOXIC: 11,
  VERIFY: 12,
  FOX_VERIFY: 13,
  MUTE: 14,
  SUNRISE: 15,
  ANNOUNCE_DEATH: 16,
  SPEECH: 17,
  VOTE: 18,
  DUEL: 19,
  PARDON: 20,
  CONFESS: 21,
  END: 22
};

goog.object.extend(exports, proto.com.nearsyh.mafia.protos);
